### PR TITLE
Merge upstream + Spot fleet updates

### PR DESCRIPTION
**Pull request by keshavdv**
Rebase from upstream master + changes from #16

### CODE REVIEW

**Comment by solarkennedy** [comment]
Not really much to review here. Shipi!

**Comment by mks-m** [comment]
if this is rebase, why are there commits from hashicorp repo in here? i would expect to only see commits relevant to spot fleet

**Comment by keshavdv** [comment]
Our master branch is ~800 commits behind upstream so all of those are also included here.

**Comment by keshavdv** [comment]
Closing and will instead merge upstream master once it's accepted

**Pull request closed without merging**
