### PR TITLE
add cancelled_running state for spot fleet

### PR DESCRIPTION
**Pull request by somic**
When I canceled a spot fleet in console, before entering "cancelled" state it first went to "cancelled_running" state.

Here we get terraform to treat both states as if this spot fleet request is gone.

### CODE REVIEW

**Comment by solarkennedy** [comment]
lgtm

**Comment by somic** [comment]
Hm, I thought it was a pattern in golang. Will revisit.

**Comment by somic** [comment]
Also will need to add "cancelled_terminating" state.

**Comment by somic** [comment]
Fixed.

**Comment by solarkennedy** [comment]
Can you rebase on master?

**Comment by somic** [comment]
going to open a new PR

**Pull request closed without merging**
